### ISSUE TITLE
Does this work on non-latin text?

### ISSUE THREAD

**Issue by xxxpsyduck** [Alpaca07/Deformable_Text_Recognition#2]
If yes, do i have to modify anything? What are these?

**Comment by yxgong0** [comment]
The network should work on non-latin text, but modification are needed in the code. 
① In line 54 of train.py, the variable 'alphabet' should be a string which contains all the characters needed to be recognized. Make sure that the length of the variable is the same as the number of characters, as some non-latin text may be expressed with more than one character.
② If there are encoding problems, please explore dataset.py and make sure the return value ‘label’ is correct. For example, encoding mode 'UTF-8' is required for Chinese.
③ For text expressed with more than one character, you need to explore utils.py, and the class 'strLabelConverter' in line 91 should be modified to ensure that the text sequences can be encoded to number sequences correctly(one character is corresponding to one integer).  And the same is needed for decode.

**Comment by xxxpsyduck** [comment]
@Alpaca07 Pytorch has it own ctc. Why do you use warp-ctc?

**Comment by yxgong0** [comment]
I got 'nan' with CTC provided by pytorch, and now this issue is still unsolved.
