### ISSUE TITLE
Question about AdaptiveMaxPool

### ISSUE THREAD

**Issue by sonnguyen129** [Alpaca07/Deformable_Text_Recognition#3]
Hi @yxgong0 
I don't understand the relationship between the output size of the AdaptiveMaxPool layer and the previous layers. Hope you will explain it to me.
Thank you so much

**Comment by yxgong0** [comment]
As a black box, AdaptiveMaxPool can be assigned an output size manually. Whatever the input size is, the output size will be the same. Therefore, the output size is fixed and independent of the previous layers.
 Please also refer to [the PyTorch document](https://pytorch.org/docs/stable/generated/torch.nn.AdaptiveMaxPool2d.html#torch.nn.AdaptiveMaxPool2d). If you would like to know how AdaptiveMaxPool did it, exploring the code of [PyTorch](https://github.com/pytorch/pytorch) may be helpful.

**Comment by sonnguyen129** [comment]
Thank you for your reply
